= Run the Decision Service in the Cloud

[#deploy]
== Deploy the decision in OpenShift

[arabic]
. Using your terminal, *login* in your OCP cluster. 
. *Access your existing project*. _(replace "your-project-name" with the name of the existing project)_:
+
[.console-input]
[source,shell]
....
oc project your-project-name
....

.. Or if you don't have a project yet, *create* one:
+
[.console-input]
[source,shell]
....
oc new-project decision-lab01
....

. On the terminal, confirm that you are in the directory of the decision service you want to deploy. If you've done the previous lab you can access:
+
[.console-input]
[source,shell]
....
cd ~/enablement/decision-lab01
....
. *Build* the _Quarkus Uberjar_
+
[.console-input]
[source,shell]
....
mvn clean package -Dquarkus.package.type=uber-jar -DskipTests
....
. *Create* a new image from binaries:
+
[.console-input]
[source,shell]
....
oc new-build registry.access.redhat.com/openjdk/openjdk-11-rhel7:latest --binary --name=base-price -l app=base-price
oc start-build base-price --from-file target/*-runner.jar --follow
....
+
Optionally, check that the _ImageStreams_ are correctly created:
+
[.console-input]
[source,shell]
....
oc get is
....
+
[.console-output]
[source,shell]
....
NAME               IMAGE REPOSITORY                                                                                                         TAGS     UPDATED
base-price         default-route-openshift-image-registry.apps.cluster-tgxrd.tgxrd.sandbox813.opentlc.com/decision-lab01/base-price         latest   33 seconds ago
openjdk-11-rhel7   default-route-openshift-image-registry.apps.cluster-tgxrd.tgxrd.sandbox813.opentlc.com/decision-lab01/openjdk-11-rhel7   latest   39 minutes ago
....
. *Create* the application:
+
[.console-input]
[source,shell]
....
oc new-app --name base-price base-price
....
. *Expose* the application (create a route)
+
[.console-input]
[source,shell]
....
oc expose svc/base-price
....

[#probe]
== Probe the decision

[arabic]
. *Retrieve* the service URL:
+
[.console-input]
[source,shell]
....
oc get route base-price -o jsonpath='{.spec.host}'
....
. If you are using the VSCode REST Client extension, you can update the url in your `.http` file to send requests to the URL result of the previous command.
. *Trigger* the REST call through *Send Request* link (right above the
`POST` line)
. *Check* that the service reply

TIP: *Alternatively,* through the `curl` command:

[.console-input]
[source,shell]
....
export URL=<your url>
curl --location --request POST $URL/pricing \
--header 'Content-Type: application/json' \
--data-raw '{ 
    "Age": 47, 
    "Previous incidents?": false    
}'
....

[#clean]
== Clean up your environment

Optionally, if you want to remove everything:

[.console-input]
[source,shell]
oc delete all -l app=base-price 
